options(warn=-1)
setwd("~/DOCS/Coursera/ExpilatoryDataAnalysis")
HPC <- read.csv("./household_power_consumption.txt", header=TRUE, sep=";", na.strings="?")
neededDate=c("1/2/2007","2/2/2007")
HPC2<-subset(HPC,HPC$Date==neededDate)
HPC2$Date <- as.Date(HPC2$Date, format="%d/%m/%Y")
HPC3<-rbind(HPC2, HPC2)
png(file = "plot1.png", bg = "transparent")
hist(HPC3$Global_active_power*2,xlab ="Global Active Power (kilowatts)", col="red", main="Global Acive Power")
dev.off()