options(warn=-1)
setwd("~/DOCS/Coursera/ExpilatoryDataAnalysis")
HPC <- read.csv("./household_power_consumption.txt", header=TRUE, sep=";", na.strings="?")
neededDate=c("1/2/2007","2/2/2007")
HPC2<-subset(HPC,HPC$Date==neededDate)
png(file = "plot4.png", bg = "transparent")
par(mfrow=c(2,2))
HPC2$Date <- strptime(paste(HPC2$Date,HPC2$Time, sep=" "), format="%d/%m/%Y %H:%M:%S")
plot(HPC2$Date,HPC2$Global_active_power,type="l",ylab="Global Active Power", xlab="Datetime")
plot(HPC2$Date,HPC2$Global_active_power,type="l",ylab="Voltage", xlab="")
plot(HPC2$Date,HPC2$Sub_metering_1,type="l",ylab="Energy sub metering", xlab="")
lines(HPC2$Date,HPC2$Sub_metering_2,type="l", col="red")
lines(HPC2$Date,HPC2$Sub_metering_3,type="l", col="blue")
legend("topright",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), col=c("black","red","blue"), lty=1)
plot(HPC2$Date,HPC2$Global_reactive_power,type="l",ylab="Global Reactive Power", xlab="Datetime")
#HPC3<-rbind(HPC2, HPC2)
#hist(HPC3$Global_active_power*2,xlab ="Global Active Power (kilowatts)", col="red", main="Global Acive Power")
dev.off()