options(warn=-1)
setwd("~/DOCS/Coursera/ExpilatoryDataAnalysis")
HPC <- read.csv("./household_power_consumption.txt", header=TRUE, sep=";", na.strings="?")
neededDate=c("1/2/2007","2/2/2007")
HPC2<-subset(HPC,HPC$Date==neededDate)
png(file = "plot2.png", bg = "transparent")
HPC2$Date <- strptime(paste(HPC2$Date,HPC2$Time, sep=" "), format="%d/%m/%Y %H:%M:%S")
plot(HPC2$Date,HPC2$Global_active_power,type="l",ylab="Global Active Power (kilowatt)", xlab="")
#HPC3<-rbind(HPC2, HPC2)
#hist(HPC3$Global_active_power*2,xlab ="Global Active Power (kilowatts)", col="red", main="Global Acive Power")
dev.off()